### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '515.3813934326172'

### ISSUE THREAD

**Issue by 152334H** [microsoft/Simplify-Docx#26]
simplify tries to convert a float to an int somewhere. 

```python
Traceback (most recent call last):
  File "/home/a/parser.py", line 14, in <module>
    doc_json = simplify(my_doc)
  File "/home/a/.local/lib/python3.10/site-packages/simplify_docx/__init__.py", line 33, in simplify
    out = document(doc.element).to_json(doc, _options)
  File "/home/a/.local/lib/python3.10/site-packages/simplify_docx/elements/base.py", line 106, in to_json
    "VALUE": [ elt.to_json(doc, options) for elt in self],
  File "/home/a/.local/lib/python3.10/site-packages/simplify_docx/elements/base.py", line 106, in <listcomp>
    "VALUE": [ elt.to_json(doc, options) for elt in self],
  File "/home/a/.local/lib/python3.10/site-packages/simplify_docx/elements/body.py", line 25, in to_json
    JSON = elt.to_json(doc, options, iter_me)
  File "/home/a/.local/lib/python3.10/site-packages/simplify_docx/elements/paragraph.py", line 169, in to_json
    out["style"] = {"indent": indentation(_indent).to_json(doc, options)}
  File "/home/a/.local/lib/python3.10/site-packages/simplify_docx/elements/base.py", line 36, in __init__
    self.props[prop] = getattr(x, prop)
  File "/home/a/.local/lib/python3.10/site-packages/docx/oxml/xmlchemy.py", line 164, in get_attr_value
    return self._simple_type.from_xml(attr_str_value)
  File "/home/a/.local/lib/python3.10/site-packages/docx/oxml/simpletypes.py", line 21, in from_xml
    return cls.convert_from_xml(str_value)
  File "/home/a/.local/lib/python3.10/site-packages/docx/oxml/simpletypes.py", line 335, in convert_from_xml
    return Twips(int(str_value))
ValueError: invalid literal for int() with base 10: '515.3813934326172'
```

The document I'm using is not meant to be shared with the public; if it's needed for debugging I'd rather send it privately

**Comment by jdthorpe** [comment]
From the call stack, you'll note that the error actually arrises in the docx package, not this package. Fairly sure that the doc you are using is out of the official docx spec.
