### ISSUE TITLE
Error parsing document with bullet list

### ISSUE THREAD

**Issue by sam2k13** [microsoft/Simplify-Docx#4]
I am trying to use this library to gather indention level from a word document. I am getting the following error when the word document includes a bullet point list...

```
Traceback (most recent call last):
  File "/home/src/main.py", line 9, in <module>
    text_groups = convert_document_to_text_groups(DOCUMENT_NAME, PATH_TO_DOCUMENT)
  File "/home/src/modules/document_converter.py", line 7, in convert_document_to_text_groups
    my_doc_as_json = simplify(document)
  File "/usr/local/lib/python3.8/site-packages/simplify_docx-0.1.0-py3.8.egg/simplify_docx/__init__.py", line 33, in simplify
    out = document(doc.element).to_json(doc, _options)
  File "/usr/local/lib/python3.8/site-packages/simplify_docx-0.1.0-py3.8.egg/simplify_docx/elements/base.py", line 106, in to_json
    "VALUE": [ elt.to_json(doc, options) for elt in self],
  File "/usr/local/lib/python3.8/site-packages/simplify_docx-0.1.0-py3.8.egg/simplify_docx/elements/base.py", line 106, in <listcomp>
    "VALUE": [ elt.to_json(doc, options) for elt in self],
  File "/usr/local/lib/python3.8/site-packages/simplify_docx-0.1.0-py3.8.egg/simplify_docx/elements/body.py", line 25, in to_json
    JSON = elt.to_json(doc, options, iter_me)
  File "/usr/local/lib/python3.8/site-packages/simplify_docx-0.1.0-py3.8.egg/simplify_docx/elements/paragraph.py", line 167, in to_json
    _indent = get_paragraph_ind(self.fragment, doc)
  File "/usr/local/lib/python3.8/site-packages/simplify_docx-0.1.0-py3.8.egg/simplify_docx/utils/paragrapy_style.py", line 56, in get_paragraph_ind
    num_style.pPr is not None and \
AttributeError: 'lxml.etree._Element' object has no attribute 'pPr'
```

I have nothing in my word document except these two lines.

![image](https://user-images.githubusercontent.com/10537834/81367343-fbbce980-90ba-11ea-8cca-29d97b57b154.png)

**Comment by jdthorpe** [comment]
Thanks for this but report.  I'll try and get to this in the next few days. (I maintain this in my "free" time)

**Comment by bighaidao** [comment]
I have the same error.  hope resolve it

> File "/Users/haidao/anaconda3/lib/python3.7/site-packages/simplify_docx/elements/body.py", line 25, in to_json
    JSON = elt.to_json(doc, options, iter_me)
  File "/Users/haidao/anaconda3/lib/python3.7/site-packages/simplify_docx/elements/paragraph.py", line 167, in to_json
    _indent = get_paragraph_ind(self.fragment, doc)
  File "/Users/haidao/anaconda3/lib/python3.7/site-packages/simplify_docx/utils/paragrapy_style.py", line 56, in get_paragraph_ind
    num_style.pPr is not None and \
AttributeError: 'lxml.etree._Element' object has no attribute 'pPr'

**Comment by hoangchunghien** [comment]
Hi @jdthorpe, this issue is similar to #12 
I have already provided a fix for this in PR. 
https://github.com/microsoft/Simplify-Docx/pull/13

Hope this helps.

**Comment by jdthorpe** [comment]
Closing this issue as it appears to be identical to issue #12.
